// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXrWT6WblTGULJnZKQX5i4uRiJHYgJO7k',
    appId: '1:491318480274:web:5b91b4040a95abc0c6054b',
    messagingSenderId: '491318480274',
    projectId: 'abiezer-app',
    authDomain: 'abiezer-app.firebaseapp.com',
    storageBucket: 'abiezer-app.appspot.com',
    measurementId: 'G-6GXCE9J7JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXrWT6WblTGULJnZKQX5i4uRiJHYgJO7k',
    appId: '1:491318480274:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '491318480274',
    projectId: 'abiezer-app',
    storageBucket: 'abiezer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXrWT6WblTGULJnZKQX5i4uRiJHYgJO7k',
    appId: '1:491318480274:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '491318480274',
    projectId: 'abiezer-app',
    storageBucket: 'abiezer-app.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.barefootbyte.abiezerCms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXrWT6WblTGULJnZKQX5i4uRiJHYgJO7k',
    appId: '1:491318480274:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '491318480274',
    projectId: 'abiezer-app',
    storageBucket: 'abiezer-app.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.barefootbyte.abiezerCms',
  );
}
